/**
 * AUTO-GENERATED by scripts/generate-schematic-constants.mjs — DO NOT EDIT.
 *
 * Source of truth:
 *   - src/lib/types.ts        (DEFAULT_THEMES, NG_COLOR_SCHEMES, THEME_NAME_SOURCE)
 *   - src/lib/config/index.ts (DEFAULT_NG_CONFIG)
 *
 * The schematics compile to CommonJS with `rootDir: "schematics"` and cannot
 * import the ESM library, so the build copies these values here. Regenerate with
 * `pnpm --filter ngx-theme-stack run generate:constants` (also runs on prebuild).
 *
 * src/schematics/generated-config.spec.ts asserts these still match the library.
 */

export const DEFAULT_THEMES = ['system', 'light', 'dark'] as const;

export const NG_COLOR_SCHEMES = ['light', 'dark', 'auto'] as const;

export const THEME_NAME_SOURCE = '^-?[a-zA-Z_][a-zA-Z0-9_-]*$';

export const DEFAULT_NG_CONFIG = {
  defaultTheme: 'system',
  storageKey: 'ngx-theme-stack',
  mode: 'class',
  strategy: 'critters',
} as const;
